name: jiffy
description: Una app para compartir fotos con música, ubicación y descripciones.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.1.1
  just_audio: ^0.9.33
  path_provider: ^2.0.12
  firebase_core: ^2.4.1
  firebase_storage: ^11.0.16
  cloud_firestore: ^4.5.1
  image_picker: ^0.8.6
  url_launcher: ^6.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
